[package]
name = 'DexlynswapLP'
version = '0.1.0'
upgrade_policy = "compatible"

[addresses]
dexlyn_swap_lp = "0x22a28a1b5264935d4778d542b1e84bca8879cf78f6183e1a9429b56a40a1a7c4"

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "aptosvm-v1.16_supra-v1.6.6"
subdir = "aptos-move/framework/supra-framework"
